name: Test Hello Action

on:
  push:

jobs:
  run-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run custom hello action
        uses: joaomvadev/hello-action@main

